### ISSUE TITLE
Allow users to generate csv

### ISSUE THREAD

**Issue by JKobyP** [JKobyP/evictiontracker#2]
Allow users to generate CSV of cases with enough information to create usable walklists.
The user should be able to select Eviction File Date date-ranges for the csv.

**Comment by tehgao** [comment]
I remember doing a little bit of work to use the google maps API to do location-aware walk list generation. Not sure if anything came of that but I'd be interested in picking up this issue regardless.

**Comment by JKobyP** [comment]
Location-aware walk-list generation isn't a priority right now because we have no problem using other service to turn spreadsheets into walklists. What's mostly needed here more specifically, is a way to generate spreadsheets based on file-date from the UI.

**Comment by JKobyP** [comment]
Resolved on v.10
